name: build_image
on:
  push:
    branches:
      - 'build/*'

jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Get branch name
        id: branch_name
        run: echo "::set-output name=tags::${GITHUB_REF#refs/heads/build/}"

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dks9467/rodi-web-v3:${{ steps.branch_name.outputs.tags }}